language: node_js
sudo: false
node_js:
  - '5'
addons:
  postgresql: '9.4'
services:
  - postgresql
before_script:
  - psql -c 'CREATE ROLE "pokedex_tracker_user" CREATEDB CREATEUSER LOGIN;' -U postgres
  - createdb -O pokedex_tracker_user pokedex_tracker
#  - npm run migrate
script:
  - npm test
  - npm run lint
after_script:
  - npm run coveralls
